import Navbar from '@/components/Navbar';
import '@/sass/global.scss';
import { Nanum_Gothic } from 'next/font/google';

const Nanum = Nanum_Gothic({
  weight: ["400", "700", "800"],
  style: "normal",
  subsets: ["latin"],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={Nanum.className}>
        <main>
          <Navbar />

          {children}
        </main>
      </body>
    </html>
  )
}
